### ISSUE TITLE
Starting date

### ISSUE THREAD

**Issue by NeoDigi** [prolificinteractive/material-calendarview#10]
In my opinion the first month to show up should be the current month, right now, it's february 1970.

**Comment by dandc87** [comment]
It looks like I didn't test the fix for bug #5 well enough :disappointed:. The master branch should have this fully fixed now, and if you have the time, @NeoDigi , please feel free to test the current snapshot (0.2.3-SNAPSHOT) from the maven central snapshot repo. I'll make sure to test this thoroughly before releasing it too.

**Comment by NeoDigi** [comment]
I didn't really check if it is the default behaviour but I added:
Calendar calendar = Calendar.getInstance();
widget.setSelectedDate(calendar.getTime());
And it return exactly what I wanted to do!
Thanks, i'll try the snapshot later today
