### ISSUE TITLE
setRangeDates unnecessarily duplicates work

### ISSUE THREAD

**Issue by langerhans** [prolificinteractive/material-calendarview#103]
Hi there, thanks for the library! I've been testing it for a while now and noticed following:

I am setting a minimumDate and a maximumDate right after each other. From looking at the MonthPagerAdapter, setRangeDates gets called once with null values, then again with the minDate and the default maxDate (today+200a), and then again with both the minDate and maxDate. Since the adapter assumes a 200 year limit, that will take a while to setup. I saw that in the method profiler.  

I would have put in a PR, but didn't know how you'd rather want to fix it. Either setting that 400 years span lower, or providing a way to initialize the view with min and max ranges (maybe in XML `minDays` and `maxDays` to allow setting a default date range?). Other option would be providing a method to set both min and max dates at the same time so it would save one call to setRangeDates, but since it gets initialized at c'tor time that doesn't make much sense to me.

**Comment by dandc87** [comment]
Hey @langerhans, I've noticed this as well. I'm working on optimizing it by generating CalendarDays on the fly instead of when the range changes. If you're curious, you can see my half baked work [here](https://github.com/prolificinteractive/material-calendarview/compare/aek/custom-views...aek/month-math). This is what I'll focus on after #99 merges.

**Comment by dandc87** [comment]
PR #105 is up, which should fix this

**Comment by dandc87** [comment]
Should be improved in version 0.8.0
