### ISSUE TITLE
Is possible to change months colors text ? 

### ISSUE THREAD

**Issue by GinesMendoza** [prolificinteractive/material-calendarview#115]
![image](https://cloud.githubusercontent.com/assets/9090336/9628362/a99a82b4-516a-11e5-9121-adf2cf4531cc.png)

I don't now why but the months color and the days are white, I would like to know if there are somehow to change this the color white to black

**Comment by dandc87** [comment]
The default styling for the header and weekdays inherit from system's default TextAppearance, so you are probably using a dark them somewhere that is messing up the colors. 

You can also supply your own TextAppearances:
* `app:mcv_headerTextAppearance` or `setHeaderTextAppearance()`
* `app:mcv_weekDayTextAppearance` or `setWeekDayTextAppearance()`
* `app:mcv_dateTextAppearance` or `setDateTextAppearance()`

If you supply a dateTextAppearance, make sure it reacts properly to presses and checks. I'm working on documenting it (#76), but you should look at the libraries `TextAppearance.MaterialCalendarWidget.Date` and make sure the color you use is an xml color selector instead of just a hex color.

**Comment by nAkhmedov** [comment]
How can i change Header side background color? I want to set multiple color to calendar, for example weekday and date sides are red, top side(header) is white. is it possible to impelement like this
![default](https://cloud.githubusercontent.com/assets/8067423/16169689/8f918dfc-3550-11e6-8b12-c2635186d97e.png)

**Comment by nAkhmedov** [comment]
@dandc87  Thanks in advance
