### ISSUE TITLE
Change the Calendar in CalenderUtils Instance

### ISSUE THREAD

**Issue by saran2somu** [prolificinteractive/material-calendarview#119]
I have my own time zone (dynamically) based Calendar . Please help me,  to change the calender as to my time zone calender .

I have try to set my calendar in CalenderUtils Class , I think it changed , but next month button is not showing , previous month works fine . Please help me to find out the issue.

Thanks in Advance

**Comment by dandc87** [comment]
Hi @saran2somu. The calendar is mostly timezone independent. It uses `CalendarDay` to represent a days internally which does not have a time zone. And any API that accepts a `Calendar` is just a convenience method for the same one that accepts a `CalendarDay`. It uses `CalendarDay.from(Calendar)` to convert from `Calendar`.

If your `Calendar` is not being converted to `CalendarDay` correctly, you will need to use `CalendarDay.from(year, month, day)` and pass that `CalendarDay` to the calendar. That said, I believe that this should not be an issue since the conversion just calls `Calendar.get()` to retrieve the year, month, and day fields.

The calendar also only returns `CalendarDay`. You will need to do convert them to you're own `Calendar` as well, since `CalendarDay.getCalendar()` assumes the device's timezone.

**Comment by saran2somu** [comment]
Thanks ... Adam Koski , I will convert my Calender to CalenderDay and let
you know.



Thanks,
Saravanan.S

On Mon, Sep 7, 2015 at 8:51 PM, Adam Koski <notifications@github.com> wrote:

> Hi @saran2somu <https://github.com/saran2somu>. The calendar is mostly
> timezone independent. It uses CalendarDay to represent a days internally
> which does not have a time zone. And any API that accepts a Calendar is
> just a convenience method for the same one that accepts a CalendarDay. It
> uses CalendarDay.from(Calendar) to convert from Calendar.
>
> If your Calendar is not being converted to CalendarDay correctly, you
> will need to use CalendarDay.from(year, month, day) and pass that
> CalendarDay to the calendar. That said, I believe that this should not be
> an issue since the conversion just calls Calendar.get() to retrieve the
> year, month, and day fields.
>
> The calendar also only returns CalendarDay. You will need to do convert
> them to you're own Calendar as well, since CalendarDay.getCalendar()
> assumes the device's timezone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prolificinteractive/material-calendarview/issues/119#issuecomment-138324262>
> .
>



-- 
S.Saravanan || +919688851518
