### ISSUE TITLE
Bottom Padding

### ISSUE THREAD

**Issue by bschnack** [prolificinteractive/material-calendarview#127]
I pulled in the MaterialCalendarView and there appears to be a ton of padding on the bottom (about the size of a tile height). Is there an easy way to get rid of that?

**Comment by dandc87** [comment]
There are some months (like August 2015) that take up 6 rows because of where the first day of the month lands. And we use a ViewPager, which is really hard to resize dynamically because it keeps multiple months in it at the same time. This mean the view needs to reserve space for all 6 rows, even if the current month doesn't need them.

I'm not saying this will _never_ get fixed, it's just a hard problem to solve since we need to account for a rather common occurrence.

In the mean time, a way you could fill up the space is to enable `showOtherDates`. This will display the next and previous month's dates. Be advised that `showOtherDates` will change to flags in the upcoming 1.0 release (see #88 #126).

**Comment by bschnack** [comment]
Thanks for the quick response.  That makes a lot more sense now, I didn't notice that. Is there a way to change the color of the text outside of the current month? I can't find anything in the documentation.  I think it would help confusion when you see the day 1 again in the view.

**Comment by dandc87** [comment]
There is new documentation in PR #135. You can look [here](https://github.com/prolificinteractive/material-calendarview/blob/doc-update/docs/CUSTOMIZATION.md) for now. It will eventually live in `/docs/CUSTOMIZATION.md`

**Comment by dandc87** [comment]
Sorry, you probably want [CUSTOM_SELECTORS.md](https://github.com/prolificinteractive/material-calendarview/blob/doc-update/docs/CUSTOM_SELECTORS.md). You're looking to change the disabled text color.
