### ISSUE TITLE
showOtherDates have trouble with "out_of_range" on other months

### ISSUE THREAD

**Issue by tsuharesu** [prolificinteractive/material-calendarview#143]
Currently I am using this flag to show dates previous today as disabled, but when I go to October, they are showing too - and this is not desirable. To me it seems that **out_of_range** is always being shown, even if **other_months** is not set.

A screenshot showing what went wrong:
![calendar_wrong](https://cloud.githubusercontent.com/assets/808267/10201058/6419bb84-6780-11e5-84af-b6780ff32333.png)

**Comment by dandc87** [comment]
@tsuharesu to clarify, you have `app:mcv_showOtherDates="out_of_range"` and have a minimum date of Sept. 30th correct? And you expect only Sept. 30th to be shown, not the every other date, correct?

**Comment by tsuharesu** [comment]
Yes, I set showOtherDates to out_of_range and the minimum date is Sep 30.

Using out_of_range I expect previous dates to show as disabled (light grey), and they are showing. But they are also showing on the next month (October) which is not what I want - Sep don't show at all in it, as you can see that Sep 30 is completely white.

**Comment by dandc87** [comment]
This is something that is part bug, part ambiguous documentation. This is happening because of the weird way I decided to order the logic of determining which days to show.

New rules will will be:
* `other_months` will imply `out_of_range`, otherwise you get weird blank areas
    * this will be a code change
* `out_of_range` will only apply to dates in the current month
    * Clarifying in code, needs to be documented clearly
* `decorated_disabled` will only apply to dates in the current month and inside the min/max range
    * Clarifying in code, needs to be documented clearly

**Comment by dandc87** [comment]
Released 1.0.1 with a fix for this.

**Comment by tsuharesu** [comment]
Fixed, thanks!
