### ISSUE TITLE
can I set a  list, and then only this list date can select

### ISSUE THREAD

**Issue by RainliFu** [prolificinteractive/material-calendarview#255]
can I set a  list, and then only this list date can select like this 

![qq 20160325112810](https://cloud.githubusercontent.com/assets/10626921/14037273/b05ac448-f27c-11e5-8894-5449fc743195.png)

**Comment by DeoMortis** [comment]
I don't know if I understand you correctly. But you can select dates like this using DayViewDecorator.
See https://github.com/prolificinteractive/material-calendarview/blob/master/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/decorators/EventDecorator.java
Instead of DotSpan create a ForegroundColorSpan with color of your liking.

Feed it with CalendarDay list form 26 to 31. I believe 25 is today, so for that another DayViewDecorator for today with color & bold.

**Comment by RainliFu** [comment]
I am sorry for that ,  For example, I think only the specified  days can choose,like this
![qq 20160328101247](https://cloud.githubusercontent.com/assets/10626921/14069522/be25dc5e-f4cd-11e5-8ec7-54c601962342.jpg)

**Comment by RainliFu** [comment]
With your help I end with this problem,thanks !
