### ISSUE TITLE
Animate layout changes when switching between week view mode and month view mode

### ISSUE THREAD

**Issue by chuks** [prolificinteractive/material-calendarview#278]
Hi,
This is an absolutely fabulous library! One question --is there a way to animate the mode switching from week mode to month mode, and vice versa? Right now, it just collapses and expands, and for an application I'm working on, it's too much of a jump. I would like to mimic the Google Calendar's layout animation when switching between modes.

**Comment by ekchang** [comment]
The transition does seem jarring. We'll look into it!

**Comment by chuks** [comment]
@ekchang Will be much appreciated!

**Comment by ekchang** [comment]
Having looked into it, the best way to accomplish this is by setting `android:animateLayoutChanges="true"` on your parent layout and setting `LayoutTransition#enableTransitionType(CHANGING)`.

I played around with adding it to the library but decided against it--mainly, it may have undesirable side effects because now MCV impacts its parent (and thus any siblings who you may not want to animate will now animate their changes).

Closing--feel free to submit a PR or comment if manually setting the transition on your parent isn't sufficient. Thanks!

**Comment by soujanyamandala** [comment]
I couldn't get it working by setting animation on parent Layout

**Comment by chuks** [comment]
Couldn't either

**Comment by soujanyamandala** [comment]
I want to add swipe up and down on material calendar view, the library already has viewpager set for scrolling right and left. Is there any way I can add swipe up and down too? When I add swipe up and down, scrolling doesn't work.
