### ISSUE TITLE
DayView is not public 

### ISSUE THREAD

**Issue by raghu42** [prolificinteractive/material-calendarview#28]
I added  compile 'com.prolificinteractive:material-calendarview:0.3.0' in my android studio, and able to access basic api's but when i tried to add DayView class in my decotors class (similar to samples), it's showing DayView class is not public. Please can you tell me why it's not public when i add library as dependency in studio, but given sample works fine with source code, as it has DayView class public.

**Comment by dandc87** [comment]
Sorry for any inconvenience, but MaterialCalendarView should be considered the only public view in this library. DayView, WeekDayView, and MonthView should all be considered internal and subject to change without warning. The reason DayView was public previously was because the library used xml layouts to construct the widget. Now in 0.3.0, it is all constructed with Java, so the visibility was reduced for the internal view classes. That change why we went from 0.2.x to 0.3.x.

An update is coming soon that will add the ability to decorate days (see #26 and #27). I hope to have it released in a few day. If this new decorator feature doesn't do what you want, please feel free to log another issue requesting what you'd like to see.

**Comment by raghu42** [comment]
Please provide the sample to use.

**Comment by dandc87** [comment]
The sample project has `BasicActivityDecorated.java` and several sample decorators.
