### ISSUE TITLE
Bug in setting a date of another year

### ISSUE THREAD

**Issue by cmercuri** [prolificinteractive/material-calendarview#407]
Hello,

I'm using this calendar and it's great! But I noticed a little bug.
In my app I have the default spinner of Android and next to it CalendarView. Below the spinner there is a button "select date", so you can choose the new date in the spinner and only clicking the button the date in the CalendarView will be changed.
If I change the day of the month or the month, everything it's ok... also if I change day of the month, month and year all together it's ok... but if I change only the year, it will not work, so the calendar change and show me the days for the date choosen, but the header will not change and it show me the "old" year.
The code is:
`historyDateCalendar.setSelectedDate(newDaySelection);
historyDateCalendar.setCurrentDate(newDaySelection);
`
`historyDateCalendar` is a MaterialCalendarView and `newDaySelection` is a java.util.Calendar.

I hope i was clear with my explanation...

Thank you in advance!

**Comment by denisko21** [comment]
I also encountered this problem. I posted pull request to fix this bug.

**Comment by EfreetSK** [comment]
The problem seems to be in class TitleChanger.java on line 57. 
`        if (currentMonth.equals(previousMonth) || currentMonth.getMonth() == previousMonth.getMonth()) {
            return;
}`
The second part of the expression (`currentMonth.getMonth() == previousMonth.getMonth()`) compares only months of current date set and new date, so if one changes just the year, it isn't recognized and the title is not refreshed. The solution is probably also to compare the years.

Is it possible to fix it or make new commit by someone like me? I'm sorry if it sounds stupid but I'm new to github or more specifically I newer updated such public project

**Comment by quentin41500** [comment]
Working now, closing!
