### ISSUE TITLE
different colors for day in EventDecorator

### ISSUE THREAD

**Issue by raplider** [prolificinteractive/material-calendarview#48]
Hi. Please tell me how to implement a different color for each date in EventDecorator

**Comment by dandc87** [comment]
Hi @raplider, the new decorator system in 0.4+ doesn't allow for individual decorating. For every color, you will need to add a Decorator that decorates that color. Be advised, adding a lot of decorators can lead to performance issues. See the [README](https://github.com/prolificinteractive/material-calendarview/blob/master/README.md#dayviewdecorator) decorator section for more information. 

This was changed from 0.3.x because calling `decorate()` for each day for each decorator caused performance issues. We believe that decorating a lot of dates the same way is more useful and desirable than decorating a lot of dates individually.
