### ISSUE TITLE
Allow customizing weekday and month names

### ISSUE THREAD

**Issue by 4KHD** [prolificinteractive/material-calendarview#6]
Thank you for creating this great library.

It would be nice if the library allows customizing the names of weekdays and months through passing the corresponding String arrays.

**Comment by dandc87** [comment]
This can definitely be a useful set of features! Here how I propose this gets implemented:

For weekday labels, we can have something like:

```java
calendarView.setWeekDayLabels(new String[] { "S", "M", ...etc... });
```

and we could add an XML attribute for this too: `app:weekDayLabels="@array/custom_labels"`

For months, we should implement something more abstract than just setting an array. Since would be used to generate a title for the calendar, we should implement something like:

```java
calendarView.setTitleFormatter(new Formatter() {
    public CharSequence format(CalendarDay date) {
        ...
    }
});
```

This would allow for a variety of formatting. We could include several "default" implementations like 'SimpleFormatter' that uses the current `SimpleDateFormat` and a 'CustomMonthFormatter' that could take an array of month labels. That one could also correspond to a new XML attribute `app:monthLabels="@array/custom_months"`

@4KHD, does this fit with what you want?

Does anyone have any feedback?
