### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by rachelxj** [prolificinteractive/material-calendarview#767]
I downloaded the latest source code , imported into Android Studio 3.1.2, I got this error
Static interface methods are only supported starting with Android N (--min-api 24): java.lang.Object com.prolificinteractive.materialcalendarview.format.DayFormatter.access$super(com.prolificinteractive.materialcalendarview.format.DayFormatter, java.lang.String, java.lang.Object[])
Message{kind=ERROR, text=Static interface methods are only supported starting with Android N (--min-api 24): java.lang.Object com.prolificinteractive.materialcalendarview.format.DayFormatter.access$super(com.prolificinteractive.materialcalendarview.format.DayFormatter, java.lang.String, java.lang.Object[]), sources=[Unknown source file], tool name=Optional.of(D8)}

the min sdk is 14, but it requires 24 to run this app?

**Comment by mgray88** [comment]
What it requires is Java 8, since DayFormatter uses a static interface method. Thankfully, according to [this](https://developer.android.com/studio/write/java8-support), you can use any sdk version to be able to use static interface methods. In that link it also shows you how to enable support for Java 8
