### ISSUE TITLE
Selection Indicator changes into oval shape.

### ISSUE THREAD

**Issue by lilsunsyn** [prolificinteractive/material-calendarview#78]
On setting setTopbarVisible() false the selection indicator circle changes into oval shape.
![ovalselector](https://cloud.githubusercontent.com/assets/7383689/8528783/20b809c4-2435-11e5-880b-c3f9b957b48e.png)

**Comment by dandc87** [comment]
@lilsunsyn this should have been fixed in `0.6.1`

**Comment by lilsunsyn** [comment]
@dandc87  thanks it looks good now. Also is there a way to design the tiles to look more like lollipop's calendar i.e. remove the extra padding below and towards the right and left. The tileSize attribute changes all the dimensions of the tile which also reduces the size of the calendar.

**Comment by dandc87** [comment]
@lilsunsyn, there isn't any extra padding added. For left and right, if you have the width as `match_parent`, it will center the calendar in the larger area. For the bottom, we need to leave space for a 5th row of days for months like the in screenshot below. The lollipop calendar can omit this row when it's not used because it does vertical scrolling, where this library uses horizontal paging.

![view-bound-screenshot](https://cloud.githubusercontent.com/assets/1239288/8534646/199ffdc8-23f3-11e5-9435-82dc71093a59.png)

**Comment by lilsunsyn** [comment]
@dandc87 okay thanks..
