### ISSUE TITLE
Differentiate showOtherDates

### ISSUE THREAD

**Issue by robertoestivill** [prolificinteractive/material-calendarview#88]
I noticed that the `showOtherDates` flag controls two things:

> 1) Completion of the calendar with dates of previous/next months 
> 2) Display of the dates outside the min/max range.

Any plans to split this functionality into two different attributes?
Thanks

**Comment by dandc87** [comment]
I was thinking of this recently too. I was playing with the idea of making it flag based instead of multiple attributes. 

By default, the calendar would, still, only show selectable dates of a single month. There would be flags to enable: days from the previous and next month, dates out of range, and days decorated as disabled.

Something like `mcv_showOtherDates="other_months|out_of_range|decorated_disabled"`

**Comment by robertoestivill** [comment]
Looks good. I think that's better than different attributes. Clever idea!

**Comment by dandc87** [comment]
This will make it into the 1.0 release. Please test out the beta (see #131)
